import { NavigationScope } from '@domain/navigation/entities/navigation-scope';
import { NavigationNodeType } from '@domain/navigation/entities/navigation-node-type';

type L = { en: string; mn: string };

interface NavigationSeedNode {
  key: string;
  parentKey?: string;
  scope: NavigationScope;
  type: NavigationNodeType;
  labels: L;
  descriptions?: L;
  href?: string;
  sortOrder: number;
  isPublished: boolean;
  metadata?: {
    imageUrl?: string;
    ctaHref?: string;
    ctaLabel?: L;
    badge?: string;
  };
}

const L = (en: string, mn: string): L => ({ en, mn });

export const DEMO_NAVIGATION_NODES: NavigationSeedNode[] = [
  // HEADER — Products mega (Stripe-style columns)
  {
    key: 'header-products',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.MEGA,
    labels: L('Products', 'Бүтээгдэхүүн'),
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-products-col-payments',
    parentKey: 'header-products',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.COLUMN,
    labels: L('Payments', 'Төлбөр'),
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-products-link-payments',
    parentKey: 'header-products-col-payments',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Payments', 'Төлбөр'),
    descriptions: L(
      'Accept and optimize online payments',
      'Онлайн төлбөр хүлээн авах',
    ),
    href: '/',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-products-link-billing',
    parentKey: 'header-products-col-payments',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Billing', 'Billing'),
    descriptions: L('Recurring revenue and subscriptions', 'Давтагдах орлого'),
    href: '/pricing',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'header-products-col-revenue',
    parentKey: 'header-products',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.COLUMN,
    labels: L('Revenue', 'Орлого'),
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'header-products-link-connect',
    parentKey: 'header-products-col-revenue',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Connect', 'Connect'),
    descriptions: L(
      'Multi-sided platform infrastructure',
      'Platform infrastructure',
    ),
    href: '/projects',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-products-link-dashboard',
    parentKey: 'header-products-col-revenue',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Admin dashboard', 'Admin dashboard'),
    descriptions: L('Enterprise RBAC admin console', 'Enterprise RBAC admin'),
    href: '/',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'header-products-sidebar',
    parentKey: 'header-products',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.SIDEBAR,
    labels: L('More', 'Бусад'),
    sortOrder: 2,
    isPublished: true,
  },
  {
    key: 'header-products-sidebar-blog',
    parentKey: 'header-products-sidebar',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Blog', 'Блог'),
    href: '/blog',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-products-cta',
    parentKey: 'header-products',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.CTA_ROW,
    labels: L('Not sure where to start?', 'Хаанаас эхлэх вэ?'),
    href: '/contact',
    sortOrder: 3,
    isPublished: true,
  },

  // HEADER — Solutions mega
  {
    key: 'header-solutions',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.MEGA,
    labels: L('Solutions', 'Шийдэл'),
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'header-solutions-startups',
    parentKey: 'header-solutions',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Startups', 'Startups'),
    descriptions: L(
      'Launch faster with production templates',
      'Production template-ээр хурдан эхлэх',
    ),
    href: '/',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-solutions-enterprises',
    parentKey: 'header-solutions',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Enterprises', 'Enterprises'),
    descriptions: L(
      'Compliance-ready regulated deployments',
      'Compliance-ready deployment',
    ),
    href: '/',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'header-solutions-saas',
    parentKey: 'header-solutions',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('SaaS', 'SaaS'),
    descriptions: L(
      'Subscription billing and usage metering',
      'Subscription billing',
    ),
    href: '/projects',
    sortOrder: 2,
    isPublished: true,
  },
  {
    key: 'header-solutions-platforms',
    parentKey: 'header-solutions',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Platforms', 'Platforms'),
    descriptions: L(
      'Marketplace and platform patterns',
      'Marketplace patterns',
    ),
    href: '/projects',
    sortOrder: 3,
    isPublished: true,
  },

  // HEADER — Developers mega
  {
    key: 'header-developers',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.MEGA,
    labels: L('Developers', 'Хөгжүүлэгчид'),
    sortOrder: 2,
    isPublished: true,
  },
  {
    key: 'header-developers-docs',
    parentKey: 'header-developers',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Documentation', 'Баримт'),
    descriptions: L('Architecture guides and ADRs', 'Architecture guides'),
    href: '/blog',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-developers-api',
    parentKey: 'header-developers',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('API reference', 'API reference'),
    descriptions: L('Versioned REST API contracts', 'REST API contracts'),
    href: '/blog',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'header-developers-guides',
    parentKey: 'header-developers',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Guides', 'Гарын авлага'),
    descriptions: L(
      'Step-by-step implementation guides',
      'Implementation guides',
    ),
    href: '/blog',
    sortOrder: 2,
    isPublished: true,
  },

  // HEADER — Resources mega
  {
    key: 'header-resources',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.MEGA,
    labels: L('Resources', 'Нөөц'),
    sortOrder: 3,
    isPublished: true,
  },
  {
    key: 'header-resources-blog',
    parentKey: 'header-resources',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Blog', 'Блог'),
    descriptions: L(
      'Product and engineering updates',
      'Product & engineering updates',
    ),
    href: '/blog',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'header-resources-stories',
    parentKey: 'header-resources',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Customer stories', 'Түүх'),
    descriptions: L(
      'Featured portfolio case studies',
      'Portfolio case studies',
    ),
    href: '/projects',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'header-resources-contact',
    parentKey: 'header-resources',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Contact', 'Холбоо барих'),
    descriptions: L(
      'Talk to us about your deployment',
      'Deployment-ийн талаар ярилцах',
    ),
    href: '/contact',
    sortOrder: 2,
    isPublished: true,
  },

  // HEADER — Pricing (root link)
  {
    key: 'header-pricing',
    scope: NavigationScope.HEADER,
    type: NavigationNodeType.LINK,
    labels: L('Pricing', 'Үнэ'),
    href: '/pricing',
    sortOrder: 4,
    isPublished: true,
  },

  // FOOTER groups
  {
    key: 'footer-products-pricing',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.GROUP,
    labels: L('Products & pricing', 'Бүтээгдэхүүн & үнэ'),
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'footer-pp-pricing',
    parentKey: 'footer-products-pricing',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Pricing', 'Үнэ'),
    href: '/pricing',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'footer-pp-payments',
    parentKey: 'footer-products-pricing',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Payments', 'Төлбөр'),
    href: '/',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'footer-pp-billing',
    parentKey: 'footer-products-pricing',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Billing', 'Billing'),
    href: '/pricing',
    sortOrder: 2,
    isPublished: true,
  },
  {
    key: 'footer-pp-connect',
    parentKey: 'footer-products-pricing',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Connect', 'Connect'),
    href: '/projects',
    sortOrder: 3,
    isPublished: true,
  },
  {
    key: 'footer-pp-dashboard',
    parentKey: 'footer-products-pricing',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Admin dashboard', 'Admin dashboard'),
    href: '/',
    sortOrder: 4,
    isPublished: true,
  },

  {
    key: 'footer-solutions',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.GROUP,
    labels: L('Solutions', 'Шийдэл'),
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'footer-sol-startups',
    parentKey: 'footer-solutions',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Startups', 'Startups'),
    href: '/',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'footer-sol-enterprises',
    parentKey: 'footer-solutions',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Enterprises', 'Enterprises'),
    href: '/',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'footer-sol-saas',
    parentKey: 'footer-solutions',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('SaaS', 'SaaS'),
    href: '/projects',
    sortOrder: 2,
    isPublished: true,
  },
  {
    key: 'footer-sol-platforms',
    parentKey: 'footer-solutions',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Platforms', 'Platforms'),
    href: '/projects',
    sortOrder: 3,
    isPublished: true,
  },

  {
    key: 'footer-developers',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.GROUP,
    labels: L('Developers', 'Хөгжүүлэгчид'),
    sortOrder: 2,
    isPublished: true,
  },
  {
    key: 'footer-dev-docs',
    parentKey: 'footer-developers',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Documentation', 'Баримт'),
    href: '/blog',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'footer-dev-api',
    parentKey: 'footer-developers',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('API reference', 'API reference'),
    href: '/blog',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'footer-dev-guides',
    parentKey: 'footer-developers',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Guides', 'Гарын авлага'),
    href: '/blog',
    sortOrder: 2,
    isPublished: true,
  },

  {
    key: 'footer-company',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.GROUP,
    labels: L('Company', 'Компани'),
    sortOrder: 3,
    isPublished: true,
  },
  {
    key: 'footer-co-blog',
    parentKey: 'footer-company',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Blog', 'Блог'),
    href: '/blog',
    sortOrder: 0,
    isPublished: true,
  },
  {
    key: 'footer-co-projects',
    parentKey: 'footer-company',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Projects', 'Төслүүд'),
    href: '/projects',
    sortOrder: 1,
    isPublished: true,
  },
  {
    key: 'footer-co-contact',
    parentKey: 'footer-company',
    scope: NavigationScope.FOOTER,
    type: NavigationNodeType.LINK,
    labels: L('Contact', 'Холбоо барих'),
    href: '/contact',
    sortOrder: 2,
    isPublished: true,
  },
];

export type { NavigationSeedNode };
