export const DEMO_PROJECTS = [
  {
    slug: 'portfolio-cms',
    title: 'Portfolio CMS',
    shortDescription: 'Full-stack portfolio with admin CMS',
    description:
      'A production-ready portfolio template built with NestJS and Next.js featuring RBAC admin panel.',
    thumbnailUrl: null,
    images: [],
    techStack: ['NestJS', 'Next.js', 'TypeORM', 'MySQL'],
    liveUrl: null,
    repoUrl: 'https://github.com/example/portfolio',
    isFeatured: true,
    isPublished: true,
    sortOrder: 0,
  },
  {
    slug: 'ecommerce-api',
    title: 'E-Commerce API',
    shortDescription: 'REST API for online store',
    description: 'Scalable e-commerce backend with payment integration.',
    thumbnailUrl: null,
    images: [],
    techStack: ['NestJS', 'PostgreSQL', 'Stripe'],
    liveUrl: null,
    repoUrl: null,
    isFeatured: false,
    isPublished: true,
    sortOrder: 1,
  },
  {
    slug: 'task-manager',
    title: 'Task Manager',
    shortDescription: 'Team task management app',
    description: 'Collaborative task board with real-time updates.',
    thumbnailUrl: null,
    images: [],
    techStack: ['React', 'Node.js', 'Socket.io'],
    liveUrl: null,
    repoUrl: null,
    isFeatured: false,
    isPublished: true,
    sortOrder: 2,
  },
];

export const DEMO_SKILLS = [
  {
    name: 'TypeScript',
    category: 'frontend',
    proficiency: 5,
    icon: 'typescript',
    sortOrder: 0,
  },
  {
    name: 'React',
    category: 'frontend',
    proficiency: 5,
    icon: 'react',
    sortOrder: 1,
  },
  {
    name: 'Next.js',
    category: 'frontend',
    proficiency: 4,
    icon: 'nextjs',
    sortOrder: 2,
  },
  {
    name: 'NestJS',
    category: 'backend',
    proficiency: 5,
    icon: 'nestjs',
    sortOrder: 3,
  },
  {
    name: 'Node.js',
    category: 'backend',
    proficiency: 5,
    icon: 'nodejs',
    sortOrder: 4,
  },
  {
    name: 'MySQL',
    category: 'backend',
    proficiency: 4,
    icon: 'mysql',
    sortOrder: 5,
  },
  {
    name: 'Docker',
    category: 'tool',
    proficiency: 4,
    icon: 'docker',
    sortOrder: 6,
  },
  { name: 'Git', category: 'tool', proficiency: 5, icon: 'git', sortOrder: 7 },
];

export const DEMO_EXPERIENCES = [
  {
    company: 'Tech Agency',
    role: 'Senior Full Stack Developer',
    location: 'Remote',
    description: 'Led development of client portfolio and SaaS projects.',
    startDate: '2022-01-01',
    endDate: null,
    isCurrent: true,
    isPublished: true,
    sortOrder: 0,
  },
  {
    company: 'Startup Inc',
    role: 'Backend Developer',
    location: 'Ulaanbaatar',
    description: 'Built REST APIs and database schemas for MVP products.',
    startDate: '2019-06-01',
    endDate: '2021-12-31',
    isCurrent: false,
    isPublished: true,
    sortOrder: 1,
  },
];

export const DEMO_SITE_SETTINGS = {
  id: 1,
  hero: {
    title: 'Hi, I am a Developer',
    subtitle: 'Full Stack Engineer',
    description: 'Building modern web applications with clean architecture.',
    ctaLabel: 'View Projects',
    ctaUrl: '/projects',
    imageUrl: null,
  },
  header: {
    logoUrl: null,
    siteName: 'Portfolio',
    navLinks: [
      { label: 'Projects', href: '/projects' },
      { label: 'Experience', href: '/experience' },
      { label: 'Contact', href: '/contact' },
    ],
  },
  footer: {
    copyright: '© 2026 Portfolio Template',
    tagline: 'Built with NestJS & Next.js',
    socialLinks: [
      { platform: 'github', url: 'https://github.com/example' },
      { platform: 'linkedin', url: 'https://linkedin.com/in/example' },
    ],
  },
  seo: {
    title: 'Portfolio | Full Stack Developer',
    description: 'Personal portfolio showcasing projects and experience.',
    ogImageUrl: null,
    keywords: ['portfolio', 'developer', 'full stack'],
  },
  contactInfo: {
    email: 'hello@example.com',
    phone: null,
    location: 'Remote',
    showForm: true,
  },
};
