export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TOKEN_ISSUER = Symbol('TOKEN_ISSUER');
export const TOKEN_BLACKLIST = Symbol('TOKEN_BLACKLIST');
export const PERMISSION_CACHE = Symbol('PERMISSION_CACHE');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const SITE_SETTING_REPOSITORY = Symbol('SITE_SETTING_REPOSITORY');
export const CONTACT_MESSAGE_REPOSITORY = Symbol('CONTACT_MESSAGE_REPOSITORY');
export const BLOG_POST_REPOSITORY = Symbol('BLOG_POST_REPOSITORY');
export const NAVIGATION_NODE_REPOSITORY = Symbol('NAVIGATION_NODE_REPOSITORY');
export const BRAND_REPOSITORY = Symbol('BRAND_REPOSITORY');
export const MENU_ITEM_REPOSITORY = Symbol('MENU_ITEM_REPOSITORY');
export const BRAND_EVENT_REPOSITORY = Symbol('BRAND_EVENT_REPOSITORY');
export const HISTORY_ENTRY_REPOSITORY = Symbol('HISTORY_ENTRY_REPOSITORY');
export const LEADERSHIP_MEMBER_REPOSITORY = Symbol(
  'LEADERSHIP_MEMBER_REPOSITORY',
);
export const TEAM_MEMBER_REPOSITORY = Symbol('TEAM_MEMBER_REPOSITORY');
export const NOTIFICATION_PORT = Symbol('NOTIFICATION_PORT');
export const MEDIA_STORAGE_PORT = Symbol('MEDIA_STORAGE_PORT');
export const MFA_VERIFIER = Symbol('MFA_VERIFIER');
export const OAUTH_IDENTITY = Symbol('OAUTH_IDENTITY');
