apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "re-cms-stack.fullname" . }}-api
  labels:
    app.kubernetes.io/name: re-cms-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: re-cms-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: re-cms-api
    spec:
      serviceAccountName: {{ include "re-cms-stack.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - secretRef:
                name: {{ include "re-cms-stack.fullname" . }}-api-secrets
            - configMapRef:
                name: {{ include "re-cms-stack.fullname" . }}-api-config
          livenessProbe:
            httpGet:
              path: /api/v1/health/live
              port: {{ .Values.api.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/health/ready
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
