apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-stack.fullname" . }}-api
spec:
  selector:
    app.kubernetes.io/name: portfolio-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
