{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portfolio-stack.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: portfolio-admin
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: portfolio-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portfolio-admin
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          envFrom:
            - secretRef:
                name: {{ include "portfolio-stack.fullname" . }}-frontend-secrets
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
