apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio-stack.fullname" . }}-frontend
spec:
  selector:
    app.kubernetes.io/name: portfolio-admin
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
